### ISSUE TITLE
Unable to get Wiimotes to stay synced!

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [WiiController/WiiController#1]
Hallo! :  ) Thank you so much for championing this program for the next generation. Before this I was using Tapesonthefloor/JustinBis's fork, which works for one player just fine. https://github.com/tapesonthefloor/wjoy-foohid However, whenever I try to sync multiple Wiimotes, they all just act as the same Wiimote-- you can't actually use them separately. Very sad.

To start off, I'm running 10.14.6, and I just disabled SIP, so I don't think that's the problem... On yours, when I try to use it, it asks me, three times in a row, to type in my username and password. After that, when I try to sync my Wiimote, it syncs, then asks for my username and password, three times in a row, and after I do so, it un-syncs.

If I try to do the Terminal "sudo" trick I used on the other fork, it will ask me ONE time each instead of three, but it'll still un-sync.

Just made myself the Administrator, to ensure it wasn't just because of my privileges or whatnot, and it still reacted the very same way. Uncertain of what else could be wrong. Thank you so much, in advance!

**Comment by ThatsJustCheesy** [comment]
Hey there!

There are a couple of things at play here different from my testing setup.

1) There could just be an issue with OS <10.15 or so. Doubtful, but I'll have to do my own testing on 10.14.6.
~~2) My main account is an administrator account. _In theory_ things should work on a standard account if an admin password is entered in the dialog, but I'll have to confirm.~~ Never mind, saw your edit!

Questions:
- You say the Wiimote syncs for a brief period. _After_ it connects, but _before_ you enter your username and password for the next three times, is the controller usable or otherwise recognized by any applications/games?
- **edit**: also, for completeness, do you know the model/firmware of your Wiimotes? I've heard of people having more problems than usual with Wii Remote Pluses (with `TR` firmware).

Please try:
  1. Remove `/Library/Extensions/wjoy.kext`: either run `rm -rf /Library/Extensions/wjoy.kext`, or in Finder, select `wjoy.kext`, then File > (holding the Option key) "Delete Immediately…".
  2. Reboot your computer.
  3. Run the WiiController app again and enter an admin password. It wants the password because it's trying to install the driver on your behalf.
  4. Once you see `wjoy.kext` appear in `/Library/Extensions`, try to use your controller. If you _don't_ see the file appear, please run `sudo cp /Applications/WiiController.app/Contents/Frameworks/WirtualJoy.framework/Versions/A/Resources/wjoy.kext /Library/Extensions` to copy it manually.
  5. If that fails, reboot again.
  6. **edit (clarifying)** Try to pair your controller with WiiController again.

Please let me know which steps work, which don't, and what manual intervention was required, if any (e.g., `cp`).

I'll have to verify the regular install process, because I now realize that I've never tried a fresh driver install from scratch while using this fork! :)

**Comment by HomeStarRunnerTron** [comment]
SO grateful for the quick response.

During the sync when it indicates, it does NOT come up in any joystick-recognizing applications or any games. So I think it's just the LED indication, and it doesn't get any farther.

Yes, my four Wiimotes are MotionPlus remotes with TR in the name! It says "Nintendo RVL-CNT-01-TR" when I pair them. Don't know if that's what you mean-- let me know if there's something ON the Wiimote I need to read to give you the model/firmware.

I did all of your steps-- the wjoy.kext appeared instantly when booting for the first time! BUT, it didn't make any difference. It still asked me to put in my password three times when I opened the app (and every time after), and everytime I sync, it asks me to put in my password three times. And if I sudo /Applications/WiiController.app/Contents/MacOS/WiiController, it still asks for my password ONCE at boot and once at sync. And still disconnects.

Right before you replied to me, I found a version of WJoy that functions perfectly (multiple Wiimotes working at the same time-- as I mentioned in my last post, other WJoys had been working, but only for one Wiimote recognized)! It's the one that other dev deleted recently... -- but he didn't delete this copy of it: https://github.com/hiddenswitch/wjoy/tree/fixed-original

The WJoyPackage.zip in the description is what I downloaded. :  ) Then I do my whole sudo /Applications/WJoy.app/Contents/MacOS/WJoy shtick in the Terminal-- _tah-dah!_

I have to say, though, your fork looks a lot more profesh'-- fingers crossed we can figure out this issue.

**Comment by ThatsJustCheesy** [comment]
Ah, I have reproduced the problem by deleting the driver and rebooting. The kext isn't getting loaded properly after being copied. As a temporary workaround, I had to run

    sudo kextunload /Library/Extensions/wjoy.kext
    sudo kextload /Library/Extensions/wjoy.kext

and restart WiiController. Then it works.

I know for a fact that there are less "quick'n'dirty" ways to get a kext installed (an installer package would be on the table). I'll have to look more into how the wjoy kext is supposed to load.

Anyway, I'm glad to hear that an older version worked for you, though also curious why. I've skimmed through changes and I noticed that the tool installation code was indeed changed between then and now.

I'll keep digging ;)

**Comment by HomeStarRunnerTron** [comment]
Boy-oh, no such luck for me!

If I try to type in what you said (and yes, there really is a /Library/Extensions/wjoy.kext in that directory-- I went so far as to drag that path into the Terminal to ensure I wasn't mis-typing anything...), this is what I get:

```
sudo kextunload /Library/Extensions/wjoy.kext 
(kernel) Kext com.alxn1.driver.wjoy not found for unload request.
Failed to unload com.alxn1.driver.wjoy - (libkern/kext) not found.

sudo kextload /Library/Extensions/wjoy.kext
/Library/Extensions/wjoy.kext failed to load - (libkern/kext) link error; check the system/kernel logs for errors or try kextutil(8).
```

And, of course, that hasn't made any difference to the app-- still runs the same. :  )

All the best, so grateful for your responses!

EDIT: Just tried again and booting up WiiController again. Got this, slightly different.

```
sudo kextunload /Library/Extensions/wjoy.kext
(kernel) Can't unload kext com.alxn1.driver.wjoy; classes have instances:
(kernel)     Kext com.alxn1.driver.wjoy class com_alxn1_driver_WirtualJoyDevice has 1 instance.
Failed to unload com.alxn1.driver.wjoy - (libkern/kext) kext is in use or retained (cannot unload).

sudo kextload /Library/Extensions/wjoy.kext
/Library/Extensions/wjoy.kext failed to load - (libkern/kext) different version/uuid already loaded; check the system/kernel logs for errors or try kextutil(8).
```

**Comment by ThatsJustCheesy** [comment]
Thanks for trying all these things for yourself, it's helpful.

Could you try again after deleting the code signature? idk the exact consequences of this for kexts but it's worth a shot.

Please copy-paste the below to delete the code signature of `wjoy.kext`. _Be careful to copy-paste the **entire command**, as a typo could result in other things being deleted._

    sudo rm -rf /Library/Extensions/wjoy.kext/Contents/_CodeSignature/

Now quit WiiController if it's running, and run the unload/reload commands again. Then start WiiController and try to pair.

**Comment by HomeStarRunnerTron** [comment]
Nuffin!

```
sudo rm -rf /Library/Extensions/wjoy.kext/Contents/_CodeSignature/

[and then that was successful...]

sudo kextunload /Library/Extensions/wjoy.kext
(kernel) Kext com.alxn1.driver.wjoy not found for unload request.
Failed to unload com.alxn1.driver.wjoy - (libkern/kext) not found.

sudo kextload /Library/Extensions/wjoy.kext
/Library/Extensions/wjoy.kext failed to load - (libkern/kext) link error; check the system/kernel logs for errors or try kextutil(8).
```

And then when I try to go back into WiiController, it still asks me to type in my password three times in a row and won't sync correctly.

EDIT: I did a little peepsy into what's INSIDE wjoy.kext...

.. and INSIDE wjoy.kext is another wjoy.kext. Inside the contents of _that_ wjoy.kext is just a normal wjoy.kext without a wjoy.kext inside of it.

... Just letting you know.

EDIT 2: I deleted the wjoy.kext inside of the wjoy.kext, and when I tried to boot up WiiController again, it re-installed the wjoy.kext inside of the wjoy.kext. Recursion much?

**Comment by ThatsJustCheesy** [comment]
Haha yup, looks like the install script just uses `cp` to re-copy the kext every time it wants to load it… resulting in a duplicate _inside of_ the kext bundle.

Give me a few days, I'm going to try keeping the driver inside of the app bundle rather than copying it to the shared `/Library/Extensions` folder. Even if it doesn't fix your problem, it will still be a quality-of-life improvement, and more maintainable going forward.

Aside: I actually, legitimately used WiiController today (Wii U Pro controller as a remote control), so that alone proves it's still useful to me—and if it's useful to me, then it's probably useful to others as well. That is why I am putting in work to get this software back on its feet.

Anyway, thanks for working with me and stay tuned, hopefully it won't take too long :)

**Comment by HomeStarRunnerTron** [comment]
Thankyouthankyou for all of your hard work! Yesterday, using the other fork, I was playing Cuphead with my brother with Wiimotes + Classic Controllers, and it totally rocked. A question-- is there anything inside of this code that could allow us to switch around any of the Generic control placements that games recognize when we plug these in? If I'm using a Wiimote + Classic Controller, it places some important buttons ON the Wiimote-- Button 0 is, like, down on the Wiimote D-pad, and Button 1 is up on the Wiimote D-pad, hahaha! If there's anyway to customize that, or outright TURN OFF all of that so I can just add whatever buttons I want to using a joystick mapper, that'd be absolutely awesome.

**Comment by ThatsJustCheesy** [comment]
I've been similarly annoyed in the past by the button number assignments—yet another thing I'd love to eventually fix :) I think I know _how_, just need to figure out exactly _what_ to change them to. (Also, it's rather funny that the Wiimote buttons still function with the Classic Controller plugged in!)

Feel free to subscribe to #2 and/or #3

**Comment by ThatsJustCheesy** [comment]
OK, pretty sure the main problem here was the OS version. Turns out that buliding a kext for an older OS release requires building with that release's SDK, which is not the case for non-kernel code.

Please try this build, which works for me under 10.14.6: [WiiController.dmg.zip](https://github.com/WiiController/WiiController/files/4808747/WiiController.dmg.zip)

It would be a good idea to quit all other variants of WJoy and WiiController, then run

    sudo kextunload -b com.alxn1.driver.wjoy

before testing.

I've also made it so that the kext loads from within the app bundle, rather than being copied to `/Library/Extensions`. The main negative side-effect, as far as I can tell, is that the app won't work until it's copied off the disk image (dmg); launching it directly from the dmg won't work because it gets mounted as read-only, and the `wjoy.kext` loader has to change the owner to `root` for the kext to be loadable.

**Comment by HomeStarRunnerTron** [comment]
OH-HOOOO, yes!! It _works_, with multiple Wiimotes and everything! And the naming convention and slicker UI is just the BEST. And I suppose your idea about making a package installer could solve those issues you're mentioning! :  )

The only issue I had was that the application originally came up with that notice about it being damaged and needing to be thrown in the Trash. I don't know what causes that-- that happens with a lot of programs I try to send people, too. At any rate, the Terminal code "xattr -cr [insert app here]" solved that in a pinch. It only asks for an admin password once at start-up, as it should!

Thank you super-dee-duper much for your help. Can't wait to help others set this up!

**Comment by ThatsJustCheesy** [comment]
Awesome, I'm going to make a couple more quality-of-life improvements and release this as v0.11.0. Thanks for your help, and enthusiasm 😛
