### ISSUE TITLE
v0.13.1 does not support Guitar Hero controller extension

### ISSUE THREAD

**Issue by rbnnn** [WiiController/WiiController#13]
I'm having issues mapping the guitar hero wiitar buttons+axis, I don't know if this controller extension is supported or if I'm editing the profile wrong. I looked through the source code and saw that there isn't much that refers specifically to wiitars, just generic extensions. Help?

**Comment by ThatsJustCheesy** [comment]
Hi! Unfortunately, I don't own that extension, and the author of WJoy seems not to have either. (There is unused code for some extensions that the actual app has never exposed, but there's no Guitar Hero one.)

Looks like it's [been documented](https://wiibrew.org/wiki/Wiimote/Extension_Controllers/Guitar_Hero_(Wii)_Guitars), and more hardware support is always nice. I could go ahead and implement it, **if you'll agree to test builds**. (I don't own the hardware, so you'd have to bear with me. Expect a few failed builds, lol). Let me know if you're interested.

**Comment by rbnnn** [comment]
I'm definitely interested and I'd be more than happy to help test your builds, whatever you need :) But I only own GH3 Les Pauls, not GHWT guitars.

**Comment by ThatsJustCheesy** [comment]
Please test [WiiController.v0.13.1.git.070edfd.dmg.zip](https://github.com/WiiController/WiiController/files/6835213/WiiController.v0.13.1.git.070edfd.dmg.zip), using something like [this](https://apps.nektro.net/gamepad/)

**Comment by rbnnn** [comment]
When plugged in without touching anything:
Axis 0: -1.000
Axis 1: 0.992

Testing buttons:
Axis 3 is associated with the whammy but only changes value and jumps to -1.000 when pressed all the way down. Also jumps to 1.000 when pulled up (which makes sense since pulling up is like pressing a button)
B.11 for Guitar minus button
B.12 for Strum down
B.17 for Red button, all values 1.000

Still no input:
Green. Yellow, Blue, Orange, Strum up, Plus and Guitar joystick

Hope that helps :)

**Comment by ThatsJustCheesy** [comment]
The buttons were a byte-order mistake. They should all work now, fingers crossed.

As for the axes, it may be a bit of a fun game getting them calibrated. I've gone ahead and removed a multiplier I copied from the U Pro controller, so moving the stick should now at least result in ±1 values. Once that's confirmed working, we can tweak that multiplier until it's good enough. Note that I'm doing the [same as the U Pro controller](https://github.com/WiiController/WiiController/wiki/Wii-U-Pro-controller-analog-stick-calibration) for stick calibration since it basically works and I don't know of a better way. As a consequence, you'll have to spin the joystick all the way around once or twice and move the whammy bar all the way (both up and down) for the calibration to happen, each time you reconnect. (Might be nice to persist that on disk in the future.)

Please test [WiiController.v0.13.1.git.9cd0af3.dmg.zip](https://github.com/WiiController/WiiController/files/6835671/WiiController.v0.13.1.git.9cd0af3.dmg.zip)

**Comment by rbnnn** [comment]
Working:
B11-18, mapped to GRYBO, Up, Down, and Plus respectively
Axis 0 and 1 - Joystick X and Y values, both are -1 ≤ x ≤ 1 depending on the joystick's position
Axis 3 - Whammy bar's the same

The only button that doesn't work is the minus button, funny because that's one of the only ones that worked before lol.

**Comment by ThatsJustCheesy** [comment]
Let's finish this up.

I'm fairly confident the minus button will work now. I'd missed listing it as a button in the event firing code.

How is the analog input calibration? Acceptable?

Please test [WiiControllerv.0.13.1.git.d483806.dmg.zip](https://github.com/WiiController/WiiController/files/6873242/WiiControllerv.0.13.1.git.d483806.dmg.zip)

**Comment by rbnnn** [comment]
All the inputs are mapped now! From B11-19. 
The analog input calibration is okay, both my Les Paul joysticks don't center at 0,0 but instead 0.062, 0.062 which might be because of joystick drift. Axis 0-1 values still reach ±1 regardless. 

Great work :) This is going to be revolutionary in the Clone Hero community, mind if I boost it in our reddit and discord?

**Comment by ThatsJustCheesy** [comment]
Awesome! I'm going to merge this, fix the code signing (I think/hope self-signing will be sufficient) and cut a release. Then feel free to spread the word, more happy users is always nice.
