### ISSUE TITLE
Wii U Pro inputs not working

### ISSUE THREAD

**Issue by AllieWade** [WiiController/WiiController#6]
I have a WIi U Pro controller that I'm trying to use on a MacBook running Catalina 10.15.7. I disabled SIP and reenabled it without kext, installed wiicontroller, and now my controller pairs successfully, but Steam Big Picture doesn't detect a controller connected and neither do my games, and none of the buttons do anything. I tried enabling input monitoring, since I recall that being required for wjoy, but still no success.

**Comment by HomeStarRunnerTron** [comment]
Hey-- so, for me, it's never detected a controller on Steam, either. I know what the description says, but I think that's mainly just copied straight from the last version of this, wJoy! For me, I use a mapper to map the buttons to keyboard keys (The one I use is called [Controllers](https://vividmachine.com/controllers/), but there's also, like, [Enjoyable](https://yukkurigames.com/enjoyable/) or [Joystick Mapper](https://joystickmapper.com/)). There are very few games that recognize my controller as an actual controller! But I'd be interested to know what the dev has to say about it being recognized by Steam! Maybe it really CAN be recognized by Steam through Big Picture Mode.

**Comment by AllieWade** [comment]
I'll give that a shot, thank you!

**Comment by ThatsJustCheesy** [comment]
Hey! Yeah, I've never had any games recognize the proxy (virtual) gamepads that this app creates. I've always just routed my inputs through Joystick Mapper. It does cost about $5 on the Mac App Store but it's been pretty reliable. I've never used Controllers or Enjoyable, but that's mainly because I've never had much of a reason to (give 'em a shot if you like).

When I say "proxy" or "virtual" gamepads, I do mean it: in the way WJoy was designed, the device driver kext does the bare minimum—basically just send/receive data to/from the Wiimotes—and then the application creates a generic "gamepad" device and routes the inputs through that. So I imagine what's going on is that most games are fairly picky about what they recognize as a controller (Xbox, maybe PS4) and they, whether by choice or ignorance, disregard the generic device.

I'd be mildly interested in somehow getting games to recognize the virtual gamepads, but it's not really a priority for me at the moment. Always happy for others to contribute though :)
Hope that clears things up!

**Comment by ThatsJustCheesy** [comment]
Oh, shoot, I can see where you might have gotten the impression that Steam Big Picture would work—I'll remove that line from the README, it's just a leftover from the wjoy fork. (That said, if you do somehow manage to get it working without a mapping utility, I'd love to know about it)

**Comment by HomeStarRunnerTron** [comment]
Hope all is welle for you-- thank you **so** much for allowing us to continue to use this program into the next generation of Mac. :  D You might want to replace that line with instructions on how to use it on things once it's been synced-- not everybody knows about this type of joystick mapping software!

**Comment by AllieWade** [comment]
I certainly didn't. Thank you all so much, I'm noodling around with Joystick Mapper now!

**Comment by ThatsJustCheesy** [comment]
Updated README to nudge users to wiki pages pertaining to this issue.
