### ISSUE TITLE
Is anyone able to use this in Big Sur?

### ISSUE THREAD

**Issue by higepon** [WiiController/WiiController#7]
Is anyone able to use this in Big Sur 11.0.1?
I tried and followed the instruction in the README, but it didn't work for me. The app silently died.

I appreciate any info. thanks!

**Comment by HomeStarRunnerTron** [comment]
Sadly, I don't think anybody here (including the dev) has Big Sur. if you can be more specific about what happened, I'm sure it'd help, though.

**Comment by higepon** [comment]
Hi thank you for your reply.
To be clear Big Sur is the latest version of macOS so hopefully some people has it installed.
Does this app have logging? I can re-run the app and paste some logging if that helps!

**Comment by ThatsJustCheesy** [comment]
First: This app relies on a kext, which (as I learned trying to support 10.14) must be built with the particular SDK for the oldest OS version you want to support. So it might require a rebuild. I've disabled arm64 architecture and triggered a rebuild of master, ~~grab the binary from here once it's done.~~ EDIT: That build failed because GitHub changed stuff. I've fixed that, here is [a successful build](https://github.com/WiiController/WiiController/actions/runs/395351984).

Second: The kext loading process changed with macOS 11 and is now significantly more complicated. The correct solution is to ditch the kext in favor of a dext, but that would drop support for <10.15 and is some nontrivial work. I hope to be able to do it eventually.

I don't have the new OS yet, but you might be able to get it working with instructions on [this page](https://developer.apple.com/documentation/apple_silicon/installing_a_custom_kernel_extension) — poke around in System Preferences, try `kextload`/`kmutil`, etc. Note that you will have to reboot your computer. Every. Time. You launch the app. (is my naive understanding, anyway, I haven't tested; but it's my best guess due to the load-on-demand architecture WiiController uses). Again, kexts are pretty much dead in macOS 11.

In the off chance you get the kext loaded successfully and there's some other issue, feel free to toss over some Console.app logs, which might provide clues.

Sorry for the disappointment!

**Comment by higepon** [comment]
Thank you so much for your detailed reply and the build.
Let me try and see if it works.

**Comment by ThatsJustCheesy** [comment]
Update: the previous build expired. [Here's a fresh one](https://github.com/WiiController/WiiController/actions/runs/692138673#artifacts). If anyone with an Intel-based Mac on macOS 11 cares enough to give it a test, that would be very helpful; as I've just explained in #9, I'm too busy with school to do so myself at the moment.

**Comment by ThatsJustCheesy** [comment]
This is hopefully resolved by #10. @higepon, if you're still interested, please try the test build: https://github.com/WiiController/WiiController/pull/10#issuecomment-830727679

In short, I've converted the kext (deprecated) to a dext (supported and recommended) for macOS 10.15 and above, including Big Sur. Older OS versions will continue to use the kext.
